config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get '/machines', to: 'machines#index'
  # get '/machines/:id', to: 'machines#show'

  resources :machines, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :bookings, only: [:index, :create, :destroy]
  end
  resources :bookings, only: [:show]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :machine
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :user
  has_many_attached :photos, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :business_name, :business_type, :location, :machine_type, :price, presence: true
  validates :business_name, length: { minimum: 3 }
  validates :business_type, inclusion: { in: ["Cafe", "Bar", "Gym", "Shopping Mall", "Coworking Spaces", "Universities", "Other"]}
  validates :machine_type, inclusion: { in: ["Washer", "Dryer", "Washer & Dryer"]}
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :machines, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :find_machine, only: [:create]

  def index
    @bookings = Booking.where(user_id: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
    @machine = Machine.where(id: Booking.find(params[:id]).machine_id)
  end

  def create
    @booking = Booking.new(booking_params)
    @machine = Machine.find(params[:machine_id])
    @booking.user = current_user
    @booking.machine = @machine
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :show
    end
  end

  def destroy
  end

private

  def booking_params
    params.require(:booking).permit(:date, :time, :user_id, :machine_id)
  end

  def find_machine
    @machine = Machine.find(params[:machine_id])
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController

  def index
    @machines = Machine.all
    filter_machines if params[:search]
    @markers = @machines.geocoded.map do |machine|
      {
        lat: machine.latitude,
        lng: machine.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { machine: machine }),
        image_url: helpers.asset_url('map-solid.png'),
        id: machine.id
      }
    end
  end


  def show
    @machine = Machine.find(params[:id])
    @booking = Booking.new
    @bookings = @machine.bookings
  end

  def new
    @machine = Machine.new
  end

  def create
    @machine = Machine.new(machine_params)
    @machine.user = current_user
    if @machine.save
      redirect_to machine_path(@machine)
    else
      render :new
    end
  end

  def edit
    @machine = Machine.find(params[:id])
  end

  def update
    @machine = Machine.find(params[:id])
    @machine.update(machine_params)
    redirect_to machine_path(@machine)
  end

  def destroy
    @machine = Machine.find(params[:id])
    @machine.destroy
    redirect_to machines_path
  end

  private

  def machine_params
    params.require(:machine).permit(:location, :business_type, :business_name, :machine_type, :price, :availability, :user_id, :description, :img, photos: [])
  end

  def filter_machines
    search = params[:search]
    # @machines = Machine.where('location ILIKE ?', "%#{search[:location]}%") unless search[:location].empty?
    @machines = Machine.near("%#{search[:location]}%", 1) unless search[:location].empty?
    unless search[:date].empty?
      @machines = Machine.joins(:bookings).where('bookings.date != ?', "#{search[:date]}")
      @date = search[:date]
    end
    # @machines = Machine.where('date ILIKE ?', "%#{search[:date]}%") unless search[:date].empty?
    # @machines = Machine.where('time ILIKE ?', "%#{search[:time]}%") unless search[:time].empty?
    unless search[:business_type].empty?
      @machines = Machine.where('business_type ILIKE ?', "#{search[:business_type]}")
      @business_type = search[:business_type]
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>all bookings</h1>

<% @bookings.each do |booking| %>
<%= booking.date %>
<% end %>

app/views/bookings/show.html.erb
<div class="confirmation mt-3">
<h2> <strong>Your booking has been confirmed for the <%= @booking.date.strftime("%d-%m-%Y") %> at <%= @machine[0].business_name %>! </strong> </h2>
<p><%=  image_tag('confirmation.gif', width: 600) %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaundryLounge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/machines/_info_window.html.erb
<h4><%= machine.business_name %></h4>
<p><%= machine.location %></p>

app/views/machines/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1467528679268-767fb756be27?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2862&q=80);">
  <div class="container mt-5">
    <div class="form-container">
      <p> Edit your machine</p>
      <br>
      <%= render 'shared/machine_form' %>
    </div>
  </div>
</div>

app/views/machines/index.html.erb
  <div class="search-bar-index">
    <%= link_to "+", new_machine_path, class: "btn btn-ghost" %><%= render 'shared/searchbar' %>
  </div>

<div class="row">
  <div class="container col-4 ml-4">
    <div class="col">
      <% @machines.each do | machine | %>
        <div id="card-product-<%= machine.id %>" class="card-product my-2">
          <%= image_tag machine.img %>
          <div class="card-product-infos">
          <%= link_to machine.business_name, machine_path(machine) %>
          <p><%= machine.location %></p>
          <p><%= machine.machine_type %></p>
          <p><%= machine.price %> EUR</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col" id="map" style="width: 100%; height: 100vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/machines/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1467528679268-767fb756be27?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2862&q=80);">
  <div class="container mt-5">
    <div class="form-container">
      <p> Add a new washing machine or dryer </p>
      <br>
      <%= render 'shared/machine_form' %>
    </div>
  </div>
</div>

app/views/machines/show.html.erb
<div class="container mt-4">
  <h1><%= @machine.business_name %></h1>
    <div id="btn-link">
      <%= link_to "View all ",  machines_path, class: 'text btn-link' %>
      <%= link_to "Edit ",  edit_machine_path, class: 'text btn-link' %>
      <%= link_to "Delete",
            machine_path(@machine), class: 'text btn-link',
            method: :delete,
            data: { confirm: "Are you sure?" } %>
  </div>
</div>


<div style="margin-bottom: 100px !important;" class="container mt-4">
  <div class="row">
    <div class="col-8 mt-3">

    <div class="booking-img-big mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url(<%= if @machine.photos[0].nil?
                'https://images.unsplash.com/photo-1509042239860-f550ce710b93?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1268&q=80'
              else
                cl_image_path @machine.photos[0].key
              end %>)">
    </div>


    <div class="booking-img-medium mt-3"style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url(<%= if @machine.photos[1].nil?
                'https://images.unsplash.com/photo-1509042239860-f550ce710b93?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1268&q=80'
              else
                cl_image_path @machine.photos[1].key
              end %>)">
    </div>

    <div class="booking-img-small mt-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
        url(<%= if @machine.photos[2].nil?
                'https://images.unsplash.com/photo-1509042239860-f550ce710b93?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1268&q=80'
              else
                cl_image_path @machine.photos[2].key
              end %>)">
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url(<%= if @machine.photos[3].nil?
                'https://images.unsplash.com/photo-1509042239860-f550ce710b93?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1268&q=80'
              else
                cl_image_path @machine.photos[3].key
              end %>)">
      </div>
      </div>
    </div>

    <div class="col-4 mt-3">
        <div class="booking mt-3">
          <div class="card-product-info">
            <div class="booking-title">
               <h2> Book your loads! </h2>
            </div>

            <div class="col px-4">
              <%= simple_form_for [@machine, @booking] do |f| %>
                <%= f.input :date,as: :date, html5: true, placeholder: 'dd/mm/yy', order: [:day, :month, :year] %>
                <%= f.input :time, placeholder: '00:00' %>

             <p><strong><%= "Your total: #{@machine.price} Euro" %></p></strong>
            <div class="row justify-content-center mt-4">

              <%= f.button :submit, 'Book', class: 'btn btn-flat' %>
              <% end %>
            </div>
            <div style="margin-top: 20px" class="justify-content-center mt-4">
              <p> <%= @machine.description %></p>
            </div>


            <div style="margin-top: 20px !important;" class="row justify-content-center mt-4">
              <p> Connect with friends! </p>
              <div class="social-links">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-whatsapp"></i></a>
                <a href="#"><i class="fab fa-telegram-plane"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1589771383100-9e0ea17554b1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80);">

  <div class="container">
    <div class="row">
      <%= render 'shared/searchbar' %>
    </div>
    <div class="row">
      <div class="col-6 mt-3">
        <div class="container mt-4">
          <h1>laundry-lounge, <strong>loads of fun</strong>!</h1>
          <p>Enjoy life while laundrying with our <strong>eco</strong> detergent included!</p>
        </div>
      </div>
      <div class="col-6 mt-1">
        <%= link_to image_tag('process.png', width: 500), "#", class: "navbar-logo" %>
      </div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <h2>Wash anywhere ...</h2>
  <div class="cards">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1551879354-08d397325b44?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2551&q=80)">
      Cafes
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1614285180156-5f225c9f621b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1268&q=80)">
      Bars
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1611094607507-8c8173e5cf33?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80)">
      Gyms
    </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1618506544551-796981666b21?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80)">
      Universities & Libraries
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1434030216411-0b793f4b4173?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80)">
      Coworking Spaces
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/flagged/photo-1567966220855-01c265f049b4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2606&q=80)">
      Shopping Malls
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="card-event" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1606207426669-d7b4fd9c942e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80)">
      <br>
      <h3>Curious about fashion trends, textile care, and upcomming loundry-lounges?</h3>
      <p>Join our Community!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipiscing elit pretium vehicula ut eleifend nulla, curae venenatis rhoncus erat neque eu interdum porta ultrices potenti orci. Donec aliquam hac lobortis placerat nibh phasellus commodo, feugiat sollicitudin eros arcu penatibus ullamcorper fusce, metus neque sem mauris bibendum tellus. Pretium urna sociis eros libero luctus placerat viverra ac diam montes, per curabitur vestibulum eleifend ultrices mus pellentesque nisl. </p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
  <%= "Made with" %><%=  image_tag('washing2.png', width: 30) %><%= "care" %>
  </div>
</div>

app/views/shared/_machine_form.html.erb
<div>
  <%= simple_form_for @machine do |f| %>
    <%= f.input :business_name, placeholder: 'Business name' %>
    <%= f.input :business_type, :collection => ["Cafe","Bar", "Gym", "Shopping Mall", "Coworking Space", "University & Library", "Other"], prompt: "Cafe, Gym, etc." %>
    <%= f.input :location, placeholder: 'Address' %>
    <%= f.input :machine_type, :collection => ["Washer", "Dryer", "Washer & Dryer"], prompt: 'Washer, Dryer, etc' %>
    <%= f.input :description, placeholder: 'Description' %>
    <%= f.input :price, placeholder: 'Amount in EUR' %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, class: 'btn btn-flat' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to image_tag('logo.png', width: 60) + " laundry-lounge", root_path, class: "navbar-logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mr-15">
          <%= link_to "events", "#", class: "nav-link" %>
        </li>
        <li class="nav-item mr-15">
          <%= link_to "laundry-blog", "#", class: "nav-link" %>
        </li>
        <li class="nav-item mr-15">
          <%= link_to "become a host", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/hawareyoudoing", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active mr-15">
          <%= link_to "events", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-15">
          <%= link_to "laundry-blog", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-15">
          <%= link_to "become a host", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to image_tag('user-regular.png', width: 30), new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="search-bar">
  <div class="container">
    <%= simple_form_for :search, method: :get, url: machines_path, wrapper: :inline_form,
      html: { class: "form-inline" }  do |f| %>
      <%= f.input :location, placeholder:
          if params[:search].nil? || params[:search][:location].nil? || params[:search][:location].empty?
            'location'
          else
            params[:search][:location]
          end
          %>
      <%= f.input :date, input_html: { value: @date }, as: :date, html5: true, label: false %>
      <%= f.input :time, placeholder: 'time' %>
      <%= f.input :business_type, collection: ["Cafe","Bar", "Gym", "Shopping Mall", "Coworking Spaces", "Universities", "Other"], selected: @business_type , prompt: "What do you fancy my love?" %>
      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>